# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171023_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='posttotag',
            unique_together=set([('post', 'tag')]),
        ),
    ]
