# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171023_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publish_date']},
        ),
    ]
