# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171122_0636'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttotag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='posttotag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttotag',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.DeleteModel(
            name='PostToTag',
        ),
    ]
