# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'blog/static/blog/imgs/'),
        ),
    ]
