# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180116_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blog/static/blog/imgs/default.svg', upload_to='blog/static/blog/imgs/'),
        ),
    ]
