# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180116_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blog/static/blog/imgs/default.svg', upload_to='blog/static/blog/imgs/'),
        ),
    ]
