# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Mężczyzna'), ('Women', 'Kobieta'), ('Other', 'Inna')], max_length=12, null=True),
        ),
    ]
